name: github-repo

on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: production
    env:
      # DigitalOcean Spaces bucket name and access key, used for terraform remote state.
      TF_VAR_region: ${{ vars.DO_STATE_BUCKET_REGION }}
      TF_VAR_bucket_name: ${{ vars.DO_STATE_BUCKET_NAME }}
      AWS_ACCESS_KEY_ID: ${{ vars.DO_SPACES_ACCESS_KEY_CI }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET_KEY_CI }}

      # Terraforms Github provider authorization
      TF_VAR_github_organization: ${{ vars._GITHUB_ORGANIZATION_NAME }}
      TF_VAR_github_repo_token: ${{ secrets._GITHUB_REPO_TOKEN }}

      # Github repository configuration.
      TF_VAR_repository_name: ${{ vars.REPOSITORY_NAME }}
      TF_VAR_repository_description: ${{ vars.REPOSITORY_DESCRIPTION }}
      TF_VAR_repository_visibility: ${{ vars.REPOSITORY_VISIBILITY }}
      TF_VAR_template_owner: ${{ vars.TEMPLATE_OWNER }}
      TF_VAR_template_repository: ${{ vars.TEMPLATE_REPOSITORY }}
      TF_VAR_is_template: ${{ vars.IS_TEMPLATE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: production
          submodules: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Generate Backend Configuration
        working-directory: terraform/03-github-repository
        run: |
          # Source the common script
          source ../../scripts/common.sh
          # Generate backend.hcl using the common function
          generate_backend_file "${{ vars.DO_STATE_BUCKET_REGION }}" "${{ vars.DO_STATE_BUCKET_NAME }}" "../backend.hcl"

      - name: Terraform Init
        working-directory: terraform/03-github-repository
        run: terraform init -backend-config ../backend.hcl -backend-config="key=foundation/github-repo/terraform.tfstate"

      - name: Terraform Plan
        working-directory: terraform/03-github-repository
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: terraform/03-github-repository
        run: terraform apply tfplan
